"""Contract `tier` partitions the 90 contract files into stages and non-stages.

P0 precondition of `.cursor/plans/solver_brain_020.plan.md` §8.4:
`all_contract_stage_ids()` returns more ids than the pipeline has stages, so any
walk over contracts must partition on `tier` or it will offer gates, sub-stage
volleys and adjudicators as dispatchable stages.

Convention is documented in
`docs/cross-cutting/stage-contracts/00-INDEX.md` (generated by
`tools/bootstrap_stage_contracts.py`).
"""

from __future__ import annotations

import pytest
import yaml

from interview_mux.artifact_dependency_graph import build_graph
from interview_mux.stage_contract import (
    ALL_TIERS,
    NON_STAGE_TIERS,
    PIPELINE_TIERS,
    all_contract_stage_ids,
    contracts_dir,
    load_contract,
)
from interview_mux.v2.config import ANALYSIS_ORDER, DELIVERY_ORDER

PIPELINE_STAGES = frozenset(ANALYSIS_ORDER) | frozenset(DELIVERY_ORDER)

# The non-stages of §8.4, by kind. Every contract file that is not one of the
# 72 pipeline stages must appear here, so a new contract file cannot quietly
# join (or dodge) the dispatchable set.
NON_STAGES: dict[str, str] = {
    "transcript_review": "gate",
    "g1_vo_pickup": "gate",
    "vo_ingest": "gate",
    "_arbiter": "meta",
    "ranking_refine": "meta",
    "transitions_refine": "meta",
    "narrative_arc_refine": "meta",
    "sdp_intent_refine": "meta",
    "sfx_prompt_refine": "meta",
    "edl_narrative_refine": "meta",
    "connector_seam_adjudicate": "meta",
    "island_cluster_structure_adjudicate": "meta",
    "junction_thought_complete": "meta",
    "junction_feel_audit": "meta",
    "sfx_brief": "meta",
    "podcast_sfx_brief": "meta",
    "sound_design_plan_init": "meta",
    "synthetic_framing_plan": "meta",
    "optimal_questions": "meta",
}


@pytest.fixture(autouse=True)
def _clear_graph_cache():
    """`build_graph()` is @lru_cache(maxsize=1) over contract YAML — never serve stale."""
    build_graph.cache_clear()
    yield
    build_graph.cache_clear()


def _raw(stage_id: str) -> dict:
    path = contracts_dir() / f"{stage_id}.yaml"
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


def _all_contract_files() -> list[str]:
    """Contract stems including `_`-prefixed ones (`all_contract_stage_ids` skips those)."""
    return sorted(p.stem for p in contracts_dir().glob("*.yaml") if p.stem != "_contract-schema")


def test_every_contract_declares_an_explicit_valid_tier():
    missing: list[str] = []
    invalid: list[str] = []
    for stage_id in _all_contract_files():
        raw = _raw(stage_id)
        tier = raw.get("tier")
        if not tier:
            missing.append(stage_id)
        elif tier not in ALL_TIERS:
            invalid.append(f"{stage_id}={tier}")
    assert missing == [], f"contracts without an explicit tier: {missing}"
    assert invalid == [], f"contracts with an unknown tier: {invalid}"


def test_pipeline_tiers_equal_the_72_stages():
    tiered = {
        stage_id
        for stage_id in all_contract_stage_ids()
        if (c := load_contract(stage_id)) and c.tier in PIPELINE_TIERS
    }
    assert len(PIPELINE_STAGES) == 72
    assert sorted(tiered - PIPELINE_STAGES) == [], "non-stage carries a pipeline tier"
    assert sorted(PIPELINE_STAGES - tiered) == [], "pipeline stage missing a pipeline tier"


def test_non_stage_contracts_are_gate_or_meta():
    non_stage_ids = {s for s in _all_contract_files() if s not in PIPELINE_STAGES}
    assert non_stage_ids == set(NON_STAGES), (
        "the non-stage contract set changed — classify new files in NON_STAGES "
        "and in docs/cross-cutting/stage-contracts/00-INDEX.md"
    )
    for stage_id, expected in NON_STAGES.items():
        tier = _raw(stage_id).get("tier")
        assert tier == expected, f"{stage_id}: tier {tier!r} != {expected!r}"
        assert tier in NON_STAGE_TIERS


def test_every_pipeline_stage_has_a_contract_file():
    ids = set(all_contract_stage_ids())
    assert sorted(PIPELINE_STAGES - ids) == []


def test_tier_sets_are_disjoint():
    assert not (PIPELINE_TIERS & NON_STAGE_TIERS)
    assert PIPELINE_TIERS | NON_STAGE_TIERS == ALL_TIERS
