#!/usr/bin/env bash
# GENERATED by tools/generate_ownership_write_checks.py — do not hand-edit.
# matrix_version=8f5b9a53a9932b4a
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
PY="${ROOT}/.venv/bin/python"
if [[ ! -x "$PY" ]]; then PY=python3; fi
"$PY" - <<'PY'
from interview_mux.artifact_ownership import DENY, disk_paths_view, matrix_version
from interview_mux.prompt_validation import STAGE_ARTIFACT_DISK_PATHS
from interview_mux.v2.config import ANALYSIS_ORDER, DELIVERY_ORDER
live = set(ANALYSIS_ORDER) | set(DELIVERY_ORDER)
assert STAGE_ARTIFACT_DISK_PATHS == disk_paths_view()
missing = sorted(live - set(STAGE_ARTIFACT_DISK_PATHS))
assert not missing, missing
stale = sorted(set(STAGE_ARTIFACT_DISK_PATHS) - live)
assert not stale, stale
assert len(DENY) >= 25
print('ownership matrix ok', matrix_version())
PY
