#!/usr/bin/env python3
"""Emit frontend custom-run artifact path set from Python CUSTOM_RUN_ARTIFACT_PATHS."""

from __future__ import annotations

import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "frontend" / "src" / "generated" / "customRunArtifactPaths.ts"
VALIDATORS_PATH = REPO / "src" / "interview_mux" / "prompt_validation.py"

_NON_CUSTOM_RUN_PATHS = frozenset(
    {
        "run_meta.json",
        "ingest/checksums.json",
        "transcript/corrections.json",
        "transcript/review_queue.json",
        "segments/nle_edits.json",
    }
)


def _validator_keys() -> list[str]:
    text = VALIDATORS_PATH.read_text(encoding="utf-8")
    block = text.split("ARTIFACT_WRITE_VALIDATORS:", 1)[1].split("def validate_artifact_write", 1)[0]
    return sorted(set(re.findall(r'"([^"]+\.json)"\s*:', block)))


def main() -> None:
    paths = [p for p in _validator_keys() if p not in _NON_CUSTOM_RUN_PATHS]
    lines = [
        "/** Auto-generated by tools/codegen_custom_run_paths.py — do not edit. */",
        "",
        "export const CUSTOM_RUN_ARTIFACT_PATHS = new Set<string>([",
    ]
    for p in paths:
        lines.append(f'  "{p}",')
    lines.append("]);")
    lines.append("")
    lines.append("export function isCustomRunArtifactPath(path: string): boolean {")
    lines.append("  return CUSTOM_RUN_ARTIFACT_PATHS.has(path);")
    lines.append("}")
    lines.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT} ({len(paths)} paths)")


if __name__ == "__main__":
    main()
