#!/usr/bin/env python3
"""Generate tools/check_ownership_matrix.sh from the ALLOW/DENY registry."""

from __future__ import annotations

from pathlib import Path


def main() -> None:
    from interview_mux.artifact_ownership import DENY, matrix_version

    root = Path(__file__).resolve().parents[1]
    out = root / "tools" / "check_ownership_matrix.sh"
    lines = [
        "#!/usr/bin/env bash",
        "# GENERATED by tools/generate_ownership_write_checks.py — do not hand-edit.",
        f"# matrix_version={matrix_version()}",
        "set -euo pipefail",
        'ROOT="$(cd "$(dirname "$0")/.." && pwd)"',
        'cd "$ROOT"',
        'PY="${ROOT}/.venv/bin/python"',
        'if [[ ! -x "$PY" ]]; then PY=python3; fi',
        '"$PY" - <<\'PY\'',
        "from interview_mux.artifact_ownership import DENY, disk_paths_view, matrix_version",
        "from interview_mux.prompt_validation import STAGE_ARTIFACT_DISK_PATHS",
        "from interview_mux.v2.config import ANALYSIS_ORDER, DELIVERY_ORDER",
        "live = set(ANALYSIS_ORDER) | set(DELIVERY_ORDER)",
        "assert STAGE_ARTIFACT_DISK_PATHS == disk_paths_view()",
        "missing = sorted(live - set(STAGE_ARTIFACT_DISK_PATHS))",
        "assert not missing, missing",
        "stale = sorted(set(STAGE_ARTIFACT_DISK_PATHS) - live)",
        "assert not stale, stale",
        f"assert len(DENY) >= {len(DENY)}",
        "print('ownership matrix ok', matrix_version())",
        "PY",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    out.chmod(0o755)
    print(f"wrote {out} ({len(DENY)} deny rows, version={matrix_version()})")


if __name__ == "__main__":
    main()
